spring.application.name=config-server

server.port=9094
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#config server configuration through : classpath
#config server ko pata chalega ki configuration kaha rakhi h
#spring.profiles.active=native
#spring.cloud.config.server.native.search-locations=classpath:/config

#enable actuator
management.endpoints.web.exposure.include=*

#configserver configuration through : git
spring.profiles.active=git
spring.cloud.config.server.git.uri=https://github.com/krrdhiraj/MindUp.git
spring.cloud.config.server.git.default-lable=main
spring.cloud.config.server.get.timeout=5
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.force-pull=true

encrypt.key="dfrtyutrtyu"

#configuration of spring RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest